/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.store.order.application.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OrderInputAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4802162071254262567L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderInputAvro\",\"namespace\":\"br.com.store.order.application.avro\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"idOrder\",\"type\":\"int\"},{\"name\":\"totalPrice\",\"type\":\"double\"},{\"name\":\"orderDate\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"idClient\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"status\",\"type\":[\"null\",\"boolean\"],\"default\":null},{\"name\":\"items\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"OrderInputItemAvro\",\"fields\":[{\"name\":\"productName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"price\",\"type\":\"double\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderInputAvro> ENCODER =
      new BinaryMessageEncoder<OrderInputAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderInputAvro> DECODER =
      new BinaryMessageDecoder<OrderInputAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OrderInputAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OrderInputAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OrderInputAvro>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OrderInputAvro to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OrderInputAvro from a ByteBuffer. */
  public static OrderInputAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String id;
  @Deprecated public int idOrder;
  @Deprecated public double totalPrice;
  @Deprecated public java.lang.String orderDate;
  @Deprecated public java.lang.String idClient;
  @Deprecated public java.lang.Boolean status;
  @Deprecated public java.util.List<br.com.store.order.application.avro.OrderInputItemAvro> items;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderInputAvro() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param idOrder The new value for idOrder
   * @param totalPrice The new value for totalPrice
   * @param orderDate The new value for orderDate
   * @param idClient The new value for idClient
   * @param status The new value for status
   * @param items The new value for items
   */
  public OrderInputAvro(java.lang.String id, java.lang.Integer idOrder, java.lang.Double totalPrice, java.lang.String orderDate, java.lang.String idClient, java.lang.Boolean status, java.util.List<br.com.store.order.application.avro.OrderInputItemAvro> items) {
    this.id = id;
    this.idOrder = idOrder;
    this.totalPrice = totalPrice;
    this.orderDate = orderDate;
    this.idClient = idClient;
    this.status = status;
    this.items = items;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return idOrder;
    case 2: return totalPrice;
    case 3: return orderDate;
    case 4: return idClient;
    case 5: return status;
    case 6: return items;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: idOrder = (java.lang.Integer)value$; break;
    case 2: totalPrice = (java.lang.Double)value$; break;
    case 3: orderDate = (java.lang.String)value$; break;
    case 4: idClient = (java.lang.String)value$; break;
    case 5: status = (java.lang.Boolean)value$; break;
    case 6: items = (java.util.List<br.com.store.order.application.avro.OrderInputItemAvro>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'idOrder' field.
   * @return The value of the 'idOrder' field.
   */
  public java.lang.Integer getIdOrder() {
    return idOrder;
  }

  /**
   * Sets the value of the 'idOrder' field.
   * @param value the value to set.
   */
  public void setIdOrder(java.lang.Integer value) {
    this.idOrder = value;
  }

  /**
   * Gets the value of the 'totalPrice' field.
   * @return The value of the 'totalPrice' field.
   */
  public java.lang.Double getTotalPrice() {
    return totalPrice;
  }

  /**
   * Sets the value of the 'totalPrice' field.
   * @param value the value to set.
   */
  public void setTotalPrice(java.lang.Double value) {
    this.totalPrice = value;
  }

  /**
   * Gets the value of the 'orderDate' field.
   * @return The value of the 'orderDate' field.
   */
  public java.lang.String getOrderDate() {
    return orderDate;
  }

  /**
   * Sets the value of the 'orderDate' field.
   * @param value the value to set.
   */
  public void setOrderDate(java.lang.String value) {
    this.orderDate = value;
  }

  /**
   * Gets the value of the 'idClient' field.
   * @return The value of the 'idClient' field.
   */
  public java.lang.String getIdClient() {
    return idClient;
  }

  /**
   * Sets the value of the 'idClient' field.
   * @param value the value to set.
   */
  public void setIdClient(java.lang.String value) {
    this.idClient = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.Boolean getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.Boolean value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'items' field.
   * @return The value of the 'items' field.
   */
  public java.util.List<br.com.store.order.application.avro.OrderInputItemAvro> getItems() {
    return items;
  }

  /**
   * Sets the value of the 'items' field.
   * @param value the value to set.
   */
  public void setItems(java.util.List<br.com.store.order.application.avro.OrderInputItemAvro> value) {
    this.items = value;
  }

  /**
   * Creates a new OrderInputAvro RecordBuilder.
   * @return A new OrderInputAvro RecordBuilder
   */
  public static br.com.store.order.application.avro.OrderInputAvro.Builder newBuilder() {
    return new br.com.store.order.application.avro.OrderInputAvro.Builder();
  }

  /**
   * Creates a new OrderInputAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderInputAvro RecordBuilder
   */
  public static br.com.store.order.application.avro.OrderInputAvro.Builder newBuilder(br.com.store.order.application.avro.OrderInputAvro.Builder other) {
    return new br.com.store.order.application.avro.OrderInputAvro.Builder(other);
  }

  /**
   * Creates a new OrderInputAvro RecordBuilder by copying an existing OrderInputAvro instance.
   * @param other The existing instance to copy.
   * @return A new OrderInputAvro RecordBuilder
   */
  public static br.com.store.order.application.avro.OrderInputAvro.Builder newBuilder(br.com.store.order.application.avro.OrderInputAvro other) {
    return new br.com.store.order.application.avro.OrderInputAvro.Builder(other);
  }

  /**
   * RecordBuilder for OrderInputAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderInputAvro>
    implements org.apache.avro.data.RecordBuilder<OrderInputAvro> {

    private java.lang.String id;
    private int idOrder;
    private double totalPrice;
    private java.lang.String orderDate;
    private java.lang.String idClient;
    private java.lang.Boolean status;
    private java.util.List<br.com.store.order.application.avro.OrderInputItemAvro> items;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.com.store.order.application.avro.OrderInputAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.idOrder)) {
        this.idOrder = data().deepCopy(fields()[1].schema(), other.idOrder);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.totalPrice)) {
        this.totalPrice = data().deepCopy(fields()[2].schema(), other.totalPrice);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.orderDate)) {
        this.orderDate = data().deepCopy(fields()[3].schema(), other.orderDate);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.idClient)) {
        this.idClient = data().deepCopy(fields()[4].schema(), other.idClient);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.items)) {
        this.items = data().deepCopy(fields()[6].schema(), other.items);
        fieldSetFlags()[6] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OrderInputAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(br.com.store.order.application.avro.OrderInputAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.idOrder)) {
        this.idOrder = data().deepCopy(fields()[1].schema(), other.idOrder);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.totalPrice)) {
        this.totalPrice = data().deepCopy(fields()[2].schema(), other.totalPrice);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.orderDate)) {
        this.orderDate = data().deepCopy(fields()[3].schema(), other.orderDate);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.idClient)) {
        this.idClient = data().deepCopy(fields()[4].schema(), other.idClient);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.items)) {
        this.items = data().deepCopy(fields()[6].schema(), other.items);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public br.com.store.order.application.avro.OrderInputAvro.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public br.com.store.order.application.avro.OrderInputAvro.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'idOrder' field.
      * @return The value.
      */
    public java.lang.Integer getIdOrder() {
      return idOrder;
    }

    /**
      * Sets the value of the 'idOrder' field.
      * @param value The value of 'idOrder'.
      * @return This builder.
      */
    public br.com.store.order.application.avro.OrderInputAvro.Builder setIdOrder(int value) {
      validate(fields()[1], value);
      this.idOrder = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'idOrder' field has been set.
      * @return True if the 'idOrder' field has been set, false otherwise.
      */
    public boolean hasIdOrder() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'idOrder' field.
      * @return This builder.
      */
    public br.com.store.order.application.avro.OrderInputAvro.Builder clearIdOrder() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalPrice' field.
      * @return The value.
      */
    public java.lang.Double getTotalPrice() {
      return totalPrice;
    }

    /**
      * Sets the value of the 'totalPrice' field.
      * @param value The value of 'totalPrice'.
      * @return This builder.
      */
    public br.com.store.order.application.avro.OrderInputAvro.Builder setTotalPrice(double value) {
      validate(fields()[2], value);
      this.totalPrice = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'totalPrice' field has been set.
      * @return True if the 'totalPrice' field has been set, false otherwise.
      */
    public boolean hasTotalPrice() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'totalPrice' field.
      * @return This builder.
      */
    public br.com.store.order.application.avro.OrderInputAvro.Builder clearTotalPrice() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderDate' field.
      * @return The value.
      */
    public java.lang.String getOrderDate() {
      return orderDate;
    }

    /**
      * Sets the value of the 'orderDate' field.
      * @param value The value of 'orderDate'.
      * @return This builder.
      */
    public br.com.store.order.application.avro.OrderInputAvro.Builder setOrderDate(java.lang.String value) {
      validate(fields()[3], value);
      this.orderDate = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'orderDate' field has been set.
      * @return True if the 'orderDate' field has been set, false otherwise.
      */
    public boolean hasOrderDate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'orderDate' field.
      * @return This builder.
      */
    public br.com.store.order.application.avro.OrderInputAvro.Builder clearOrderDate() {
      orderDate = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'idClient' field.
      * @return The value.
      */
    public java.lang.String getIdClient() {
      return idClient;
    }

    /**
      * Sets the value of the 'idClient' field.
      * @param value The value of 'idClient'.
      * @return This builder.
      */
    public br.com.store.order.application.avro.OrderInputAvro.Builder setIdClient(java.lang.String value) {
      validate(fields()[4], value);
      this.idClient = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'idClient' field has been set.
      * @return True if the 'idClient' field has been set, false otherwise.
      */
    public boolean hasIdClient() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'idClient' field.
      * @return This builder.
      */
    public br.com.store.order.application.avro.OrderInputAvro.Builder clearIdClient() {
      idClient = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.Boolean getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public br.com.store.order.application.avro.OrderInputAvro.Builder setStatus(java.lang.Boolean value) {
      validate(fields()[5], value);
      this.status = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public br.com.store.order.application.avro.OrderInputAvro.Builder clearStatus() {
      status = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'items' field.
      * @return The value.
      */
    public java.util.List<br.com.store.order.application.avro.OrderInputItemAvro> getItems() {
      return items;
    }

    /**
      * Sets the value of the 'items' field.
      * @param value The value of 'items'.
      * @return This builder.
      */
    public br.com.store.order.application.avro.OrderInputAvro.Builder setItems(java.util.List<br.com.store.order.application.avro.OrderInputItemAvro> value) {
      validate(fields()[6], value);
      this.items = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'items' field has been set.
      * @return True if the 'items' field has been set, false otherwise.
      */
    public boolean hasItems() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'items' field.
      * @return This builder.
      */
    public br.com.store.order.application.avro.OrderInputAvro.Builder clearItems() {
      items = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderInputAvro build() {
      try {
        OrderInputAvro record = new OrderInputAvro();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.idOrder = fieldSetFlags()[1] ? this.idOrder : (java.lang.Integer) defaultValue(fields()[1]);
        record.totalPrice = fieldSetFlags()[2] ? this.totalPrice : (java.lang.Double) defaultValue(fields()[2]);
        record.orderDate = fieldSetFlags()[3] ? this.orderDate : (java.lang.String) defaultValue(fields()[3]);
        record.idClient = fieldSetFlags()[4] ? this.idClient : (java.lang.String) defaultValue(fields()[4]);
        record.status = fieldSetFlags()[5] ? this.status : (java.lang.Boolean) defaultValue(fields()[5]);
        record.items = fieldSetFlags()[6] ? this.items : (java.util.List<br.com.store.order.application.avro.OrderInputItemAvro>) defaultValue(fields()[6]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderInputAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderInputAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderInputAvro>
    READER$ = (org.apache.avro.io.DatumReader<OrderInputAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
